#!/usr/bin/env node

/**
 * 🕷️  Gallery Watcher — Auto-detect, register & push new photos.
 *
 * HOW IT WORKS:
 *   1. Watches  src/assets/gallery/photos/  for new image files
 *   2. Regenerates  src/data/galleryData.js  with proper imports
 *   3. Runs  git add → commit → push
 *
 * USAGE:
 *   node scripts/gallery-watcher.js          (watches continuously)
 *   node scripts/gallery-watcher.js --once   (scans once and exits)
 *
 * DROP FOLDER:
 *   src/assets/gallery/photos/
 *   (Created automatically on first run if it doesn't exist)
 */

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

// ── Paths ──────────────────────────────────────────────────
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');

const PHOTOS_DIR = path.join(ROOT, 'src', 'assets', 'gallery', 'photos');
const DATA_FILE = path.join(ROOT, 'src', 'data', 'galleryData.js');

// Supported image extensions
const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.gif', '.svg']);

// ── Helpers ────────────────────────────────────────────────

/** Ensure the photos drop-folder exists */
function ensurePhotosDir() {
  if (!fs.existsSync(PHOTOS_DIR)) {
    fs.mkdirSync(PHOTOS_DIR, { recursive: true });
    console.log(`📁  Created drop folder: ${PHOTOS_DIR}`);
  }
}

/** Sanitize a filename: replace spaces/parens/special chars with underscores */
function sanitizeFilename(filename) {
  const ext = path.extname(filename);
  const name = path.basename(filename, ext);
  const clean = name
    .replace(/[() ]+/g, '_')       // parens and spaces → underscore
    .replace(/[^a-zA-Z0-9_.-]/g, '_') // any other special chars → underscore
    .replace(/_+/g, '_')           // collapse multiple underscores
    .replace(/^_|_$/g, '');        // trim leading/trailing underscores
  return `${clean}${ext.toLowerCase()}`;
}

/** Rename any files with problematic characters */
function sanitizeAllFilenames() {
  if (!fs.existsSync(PHOTOS_DIR)) return;
  const files = fs.readdirSync(PHOTOS_DIR);
  for (const file of files) {
    if (!IMAGE_EXTS.has(path.extname(file).toLowerCase())) continue;
    const sanitized = sanitizeFilename(file);
    if (sanitized !== file) {
      const oldPath = path.join(PHOTOS_DIR, file);
      const newPath = path.join(PHOTOS_DIR, sanitized);
      fs.renameSync(oldPath, newPath);
      console.log(`🔧  Renamed: ${file} → ${sanitized}`);
    }
  }
}

/** Get sorted list of image files in the photos folder */
function getImageFiles() {
  if (!fs.existsSync(PHOTOS_DIR)) return [];

  sanitizeAllFilenames();

  return fs
    .readdirSync(PHOTOS_DIR)
    .filter((f) => IMAGE_EXTS.has(path.extname(f).toLowerCase()))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
}

/**
 * Turn a filename into a human-readable title.
 *   "sunset_at_beach.jpg"  →  "Sunset At Beach"
 *   "IMG_20260625.png"     →  "Img 20260625"
 */
function filenameToTitle(filename) {
  const name = path.basename(filename, path.extname(filename));
  return name
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

/**
 * Make a safe JS variable name from a filename.
 *   "my-photo_01.jpg"  →  "myPhoto01"
 */
function filenameToVarName(filename, index) {
  const name = path.basename(filename, path.extname(filename));
  const cleaned = name
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_([a-z])/g, (_, c) => c.toUpperCase());

  // Ensure it starts with a letter
  const varName = /^[a-zA-Z]/.test(cleaned) ? cleaned : `photo${cleaned}`;
  return `${varName}_${String(index + 1).padStart(3, '0')}`;
}

/** Regenerate galleryData.js from the current photos folder contents */
function regenerateGalleryData() {
  const files = getImageFiles();

  // Build import statements and data entries
  const imports = [];
  const entries = [];

  files.forEach((file, i) => {
    const varName = filenameToVarName(file, i);
    const id = String(i + 1).padStart(3, '0');
    const title = filenameToTitle(file);

    imports.push(`import ${varName} from '../assets/gallery/photos/${file}';`);
    entries.push(
      [
        `  {`,
        `    id: '${id}',`,
        `    src: ${varName},`,
        `    title: '${title.replace(/'/g, "\\'")}',`,
        `    meta: '',`,
        `  }`,
      ].join('\n')
    );
  });

  const code = [
    `/**`,
    ` * Gallery Data — Spider-Noir Personal Archive (Earth-90214)`,
    ` *`,
    ` * ⚡ AUTO-GENERATED by gallery-watcher.js`,
    ` * ⚡ Do NOT edit manually — drop photos into src/assets/gallery/photos/`,
    ` */`,
    ``,
    ...imports,
    ``,
    `export const galleryData = [`,
    entries.join(',\n'),
    `];`,
    ``,
  ].join('\n');

  fs.writeFileSync(DATA_FILE, code, 'utf-8');
  console.log(`📝  Updated galleryData.js  (${files.length} photo${files.length !== 1 ? 's' : ''})`);
}

/** Git add, commit, push */
function gitPush(files) {
  try {
    const fileNames = files.join(', ');
    const commitMsg = `📸 gallery: auto-add ${files.length} photo${files.length !== 1 ? 's' : ''} (${fileNames})`;

    // Stage the photos folder + data file
    execSync('git add src/assets/gallery/photos/ src/data/galleryData.js', {
      cwd: ROOT,
      stdio: 'pipe',
    });

    // Check if there's anything to commit
    const status = execSync('git diff --cached --name-only', {
      cwd: ROOT,
      encoding: 'utf-8',
    }).trim();

    if (!status) {
      console.log('⏭️   No changes to commit.');
      return;
    }

    execSync(`git commit -m "${commitMsg}"`, { cwd: ROOT, stdio: 'pipe' });
    console.log(`✅  Committed: ${commitMsg}`);

    execSync('git push', { cwd: ROOT, stdio: 'pipe' });
    console.log('🚀  Pushed to GitHub!');
  } catch (err) {
    console.error('❌  Git error:', err.stderr?.toString() || err.message);
  }
}

// ── Main ───────────────────────────────────────────────────

function scanAndSync() {
  const before = getImageFiles();
  regenerateGalleryData();

  if (before.length > 0) {
    gitPush(before);
  } else {
    console.log('📭  No photos found yet. Drop images into:');
    console.log(`    ${PHOTOS_DIR}`);
  }
}

function watch() {
  ensurePhotosDir();

  console.log('');
  console.log('🕷️  ═══════════════════════════════════════════════════');
  console.log('    GALLERY WATCHER — Spider-Noir Archive (Earth-90214)');
  console.log('   ═══════════════════════════════════════════════════');
  console.log('');
  console.log(`👁️   Watching: ${PHOTOS_DIR}`);
  console.log('📌  Drop an image file and it will be auto-registered + pushed.');
  console.log('    Press Ctrl+C to stop.');
  console.log('');

  // Initial scan
  scanAndSync();

  // Debounce — batch rapid file drops into a single update
  let debounceTimer = null;

  fs.watch(PHOTOS_DIR, { persistent: true }, (eventType, filename) => {
    if (!filename) return;

    const ext = path.extname(filename).toLowerCase();
    if (!IMAGE_EXTS.has(ext)) return;

    console.log(`\n🔔  Detected: ${filename}  (${eventType})`);

    // Debounce 2 seconds — so dropping multiple files at once
    // only triggers one regenerate + push cycle
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      const files = getImageFiles();
      regenerateGalleryData();
      gitPush(files.map((f) => path.basename(f)));
    }, 2000);
  });
}

// ── Entry point ────────────────────────────────────────────
const args = process.argv.slice(2);

if (args.includes('--once')) {
  ensurePhotosDir();
  scanAndSync();
} else {
  watch();
}
